### ISSUE TITLE
关于数据库

### ISSUE THREAD

**Issue by gx8201** [GeorGeWzw/Sukt.Core#2]
恕在下愚钝 , 请问sqlserver数据库咋连接 , 上个版本还是sqlserver

**Comment by GeorGeWzw** [comment]
n你看下里面的压缩包，压缩包里面的是Sqlserver的

**Comment by gx8201** [comment]
不好意思刚看到 多谢 还有就是readme留得博客地址404了

**Comment by GeorGeWzw** [comment]
@gx8201 好的，我改一下，忘记回复你了
